import * as React from "react";
import { ScrollView } from "react-native";
import CtfCard from "./CtfCard";

const ctfs = [
  {
    organizers: [
      {
        id: 163107,
        name: "Security Research Summit (SRS)",
      },
    ],
    onsite: false,
    finish: "2021-11-15T16:00:00+00:00",
    description:
      "The CTF competition hosted by Intent. The Security Research Summit.\r\nFor researchers. By researchers.",
    weight: 0.0,
    title: "Intent CTF 2021",
    url: "https://ctf.intentsummit.org/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-13T16:00:00+00:00",
    participants: 37,
    ctftime_url: "https://ctftime.org/event/1454/",
    location: "",
    live_feed: "https://ctftime.org/live/1454/",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "https://ctftime.org//media/events/intent_i.png",
    format_id: 1,
    id: 1454,
    ctf_id: 672,
  },
  {
    organizers: [{ id: 30003, name: "SPbCTF" }],
    onsite: false,
    finish: "2021-11-14T18:00:00+00:00",
    description:
      "Student CTF is a novice-level Capture The Flag organized by SPbCTF and supported by St. Petersburg Committee for Science and Higher Education.\r\n\r\nFree-to-play track is open to everyone, and Official track is for teams of 5 students in Saint Petersburg.\r\nBoth tracks are Jeopardy quals and Attack-Defense final round\u2014in separate scoreboards.\r\n\r\nFree-to-play track scoreboard will be uploaded to CTFtime.\r\n",
    weight: 25.0,
    title: "SPbCTF's Student CTF 2021 Finals",
    url: "https://student.ctf.su/",
    is_votable_now: false,
    restrictions: "Prequalified",
    format: "Attack-Defense",
    start: "2021-11-14T09:00:00+00:00",
    participants: 0,
    ctftime_url: "https://ctftime.org/event/1379/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 9, days: 0 },
    logo: "https://ctftime.org//media/events/studentctf2021_1.jpg",
    format_id: 2,
    id: 1379,
    ctf_id: 556,
  },
  {
    organizers: [{ id: 2003, name: "SYPER" }],
    onsite: false,
    finish: "2021-11-18T18:00:00+00:00",
    description:
      "With the support of National University of La Plata in Argentina, MetaRed Argentina is responsible for organizing this, the 4th stage of the MetaRed International CTF 2021. \r\n\r\nGeneral CTF URL: coming soon\r\n\r\nIn the 4th stage of the 2021 MetaRed International CTF the competition will be based around two different areas which will share exercises with distinct levels of graded difficulty.\r\n\r\n1. Free and Global Competition, in which any team may enrol and participate.\r\n\r\n2. Competition confined to MetaRed IES, in which participants will have to prove through their enrolment that they belong to an Ibero-American Institution of Higher Education.",
    weight: 0.0,
    title: "MetaRed International CTF 2021 - 4th STAGE",
    url: "https://eventos.metared.org/69247/detail/ctf-internacional-metared-2021-4th-stage.html",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-17T18:00:00+00:00",
    participants: 8,
    ctftime_url: "https://ctftime.org/event/1489/",
    location: "",
    live_feed: "",
    public_votable: false,
    duration: { hours: 0, days: 1 },
    logo: "",
    format_id: 1,
    id: 1489,
    ctf_id: 653,
  },
  {
    organizers: [{ id: 125608, name: "Hackfest.ca" }],
    onsite: false,
    finish: "2021-11-20T08:00:00+00:00",
    description:
      "This year our infamous CTF will be split into 2 separate scoreboards sharing the same tracks and challenges:\r\n\r\n- A Casual Scoreboard with very cool hacker-themed prizes\r\n- A Competitive Scoreboard with cash prizes\r\n\r\nThis is the CTF Time page for the COMPETITIVE scoreboard. Make sure you register to the right event. \r\n\r\nRegistration link: https://www.eventbrite.ca/e/hf-ctf-competitive-2021-tickets-194868927207\r\n\r\nWe won't accept any request of transfer from a scoreboard to the other, you'll need to purchase a new ticket.\r\n\r\nPlease note:\r\n\r\n- You MUST join the official Hackfest Discord server (https://discord.hackfest.ca) in order to participate in the CTF. On the day of the event, you'll need to sign in to the scoreboard using your Discord account.\r\n- The Hackfest CTF is a team event, we accept teams of 1, 2, 3 or 4. You'll be asked to join or create a team at the beginning, you can log back in to EventBrite to edit this information until November 17.\r\n\r\nFurther details will be announced on Discord.\r\n",
    weight: 25.0,
    title: "Hackfest CTF 13th Edition - Competitive",
    url: "https://hackfest.ca/en/ctf/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-19T20:00:00+00:00",
    participants: 1,
    ctftime_url: "https://ctftime.org/event/1498/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 12, days: 0 },
    logo: "https://ctftime.org//media/events/Logo_CTF_5.png",
    format_id: 1,
    id: 1498,
    ctf_id: 473,
  },
  {
    organizers: [{ id: 19208, name: "Nu1L" }],
    onsite: false,
    finish: "2021-11-22T00:00:00+00:00",
    description:
      "N1CTF is a 48-hour jeopardy style CTF held by members of Nu1L.",
    weight: 53.54,
    title: "N1CTF 2021",
    url: "https://ctf2021.nu1l.com/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-20T00:00:00+00:00",
    participants: 43,
    ctftime_url: "https://ctftime.org/event/1367/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "",
    format_id: 1,
    id: 1367,
    ctf_id: 240,
  },
  {
    organizers: [{ id: 46747, name: "Square" }],
    onsite: false,
    finish: "2021-11-21T01:00:00+00:00",
    description:
      "Annual CTF organized by Square. Puzzles range from easy (welcome new comers!) to hard.",
    weight: 30.75,
    title: "Square CTF 2021",
    url: "https://squarectf.com/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-20T01:00:00+00:00",
    participants: 13,
    ctftime_url: "https://ctftime.org/event/1496/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 1 },
    logo: "",
    format_id: 1,
    id: 1496,
    ctf_id: 218,
  },
  {
    organizers: [{ id: 16978, name: "Balsn" }],
    onsite: false,
    finish: "2021-11-22T02:00:00+00:00",
    description:
      "Registration: TBD\r\nOrganizers: Balsn (https://balsn.tw/)\r\nTwitter: @balsnctf (https://twitter.com/balsnctf)",
    weight: 37.0,
    title: "Balsn CTF 2021",
    url: "https://balsn.tw/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-20T02:00:00+00:00",
    participants: 34,
    ctftime_url: "https://ctftime.org/event/1376/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "https://ctftime.org//media/events/circle.400dpi_2.png",
    format_id: 1,
    id: 1376,
    ctf_id: 318,
  },
  {
    organizers: [{ id: 104940, name: "ACISO" }],
    onsite: false,
    finish: "2021-11-21T09:00:00+00:00",
    description:
      "CTF Russian Cup 2021 Quals event. Russian academic teams only.",
    weight: 0,
    title: "CTF Russian Cup 2021",
    url: "https://aciso.timepad.ru/event/1814641/",
    is_votable_now: false,
    restrictions: "Academic",
    format: "Jeopardy",
    start: "2021-11-20T09:00:00+00:00",
    participants: 8,
    ctftime_url: "https://ctftime.org/event/1479/",
    location: "",
    live_feed: "",
    public_votable: false,
    duration: { hours: 0, days: 1 },
    logo: "https://ctftime.org//media/events/cup.jpg",
    format_id: 1,
    id: 1479,
    ctf_id: 229,
  },
  {
    organizers: [{ id: 158405, name: "LowLandMink543" }],
    onsite: false,
    finish: "2021-11-27T19:00:00+00:00",
    description:
      "This is the first CTF from LLM. These are Very easy Challenges that allow beginners to take place. To be verified, please email CTF@austinh.dev",
    weight: 0.0,
    title: "LLM CTF",
    url: "http://austinh.dev/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-23T19:00:00+00:00",
    participants: 6,
    ctftime_url: "https://ctftime.org/event/1478/",
    location: "",
    live_feed: "https://ctftime.org/live/1478/",
    public_votable: false,
    duration: { hours: 0, days: 4 },
    logo: "",
    format_id: 1,
    id: 1478,
    ctf_id: 651,
  },
  {
    organizers: [{ id: 162693, name: "DSPH" }],
    onsite: false,
    finish: "2021-11-25T12:00:00+00:00",
    description:
      "Damncon2021 is the cyber conference organized by Damn Secure Pentesting Hub, It is annual event with the mission to change your vision towards the domain of cybersecurity. All the uses are requested to read the rules and regulations before starting your CTF Events.\r\n\r\nEvents Sponsor:- Bugcrowd, Burpbounty, HTB, 1password, Givemycertificate, nulltrace",
    weight: 0.0,
    title: "Damncon 2021",
    url: "https://damncon2021.nulltrace.in/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-24T12:00:00+00:00",
    participants: 6,
    ctftime_url: "https://ctftime.org/event/1481/",
    location: "",
    live_feed: "https://ctftime.org/live/1481/",
    public_votable: true,
    duration: { hours: 0, days: 1 },
    logo: "https://ctftime.org//media/events/1179a90577b0595b40de0924d9a6d9da372098_prev_ui.png",
    format_id: 1,
    id: 1481,
    ctf_id: 684,
  },
  {
    organizers: [{ id: 9831, name: "CCSIR.org" }],
    onsite: false,
    finish: "2021-11-28T15:00:00+00:00",
    description:
      "DefCamp Capture The Flag ( D-CTF) is the most shattering and rebellious security CTF competition in the Central Eastern Europe.\r\n\r\nHere, the most skilled hackers & IT geeks put their knowledge to the test and compete with the best CFT teams from all over the world to get in the shortlist of best top 10, and later on win the overall D-CTF competition or, die trying.\r\n\r\nDefCamp Capture the Flag is organised since 2011 with over 10,000 players joined since then in annual multi-staged event for anyone.\r\n\r\nThere is one important rule though \u2013 hack before being hacked! \r\n\r\nBecause challenges are inspired by real life scenarios from day-to-day challenges of industry experts and other CTF players, you have to prove the ability to develop skills and under stress. It will be fun, I promise! :-)\r\n\r\nDefCamp CTF 2021 is going to be organised online only in 2021.\r\n\r\nRegistration: https://dctf21.cyberedu.ro/",
    weight: 0.0,
    title: "DefCamp CTF 2021 Online",
    url: "https://dctf21.cyberedu.ro/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-26T09:00:00+00:00",
    participants: 2,
    ctftime_url: "https://ctftime.org/event/1502/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 6, days: 2 },
    logo: "https://ctftime.org//media/events/dctf_2.png",
    format_id: 1,
    id: 1502,
    ctf_id: 73,
  },
  {
    organizers: [{ id: 140885, name: "The Few Chosen" }],
    onsite: false,
    finish: "2021-11-28T12:00:00+00:00",
    description:
      'The Few Chosen organizes its first CTF event between 26th-28th November. We are a group of 5 students that have participated in numerous CTFs, and our passion for cybersecurity encouraged us to host our own.\r\n\r\nWe have developed the website from the ground up to ensure that the participants will have the best experience. We are going to have challenges from Pwn, Reverse, Web, Crypto, Misc. The CTF is for everyone, no matter the knowledge, as the challenges are rated from "Warmup" to "Hard". This CTF is the perfect occasion for beginners to learn their way through cybersecurity and experts who want to test their skills.\r\n\r\nSponsors:\r\n- Wolfram Alpha\r\n* (more to come)',
    weight: 0.0,
    title: "TFC CTF 2021",
    url: "https://ctf.thefewchosen.com/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-26T12:00:00+00:00",
    participants: 16,
    ctftime_url: "https://ctftime.org/event/1501/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "https://ctftime.org//media/events/discord_logo.png",
    format_id: 1,
    id: 1501,
    ctf_id: 696,
  },
  {
    organizers: [{ id: 144070, name: "Securebug" }],
    onsite: false,
    finish: "2021-11-28T14:00:00+00:00",
    description:
      "SecureBug is organizing another CTF.\r\nEnjoy with your friends solving a number of challenges in different categories varying from basic to hard level. \r\nThis CTF is for Digital Forensics, Web security, Cryptography,OSINT and reverse engineering to test and enhance your technical skills. \r\nIt will be in a Jeopardy Style where every team/Hunter will have a list of challenges. \r\nFor every challenge solved, the team/Hunter will get a certain amount of points depending on the difficulty of the challenge.\r\nConditions\r\nAll talents can participate without any adherence to age, nationality, or skill level.\r\nInformation regarding teamwork:\r\nIf you wish to add teammembers you can add them on your profile detail section on the platform.\r\nImportant that only one teammember submits the flags.\r\n\r\nRules:\r\n\r\nRules concerning the platform are included:\r\n\u2013 Sharing the flags between players is not allowed\r\n\u2013 Brute Force attacks on the challenges submission portal or challenges links are not allowed.\r\n\u2013 Any attack against the site or the hosted servers will be observed and the player will be banned from participating in the CTF immediately.\r\n\u2013 Organizer has the permission to disqualify players for any unethical behavior or any trials to interrupt the CTF\r\n",
    weight: 0.0,
    title: "Securebug.se CTF Thor 2021",
    url: "https://securebug.se/thor/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-26T14:00:00+00:00",
    participants: 9,
    ctftime_url: "https://ctftime.org/event/1448/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "",
    format_id: 1,
    id: 1448,
    ctf_id: 586,
  },
  {
    organizers: [{ id: 48677, name: "RedRocket" }],
    onsite: false,
    finish: "2021-11-28T20:00:00+00:00",
    description:
      "The (Cyber) CyberSecurityRumble Germany is back!\r\n\r\nThe CSR this year will be a 48h online Jeopardy style CTF.\r\n**Max Team size is 6 Hackers!**\r\nEverybody is allowed to participate online.\r\n\r\nAgain we'll have tasks in all categories: pwn, rev, crypto, web, ... from beginner friendly to 31337!\r\n\r\nNext year we'll hopefully have an onsite final again!",
    weight: 41.6,
    title: "CyberSecurityRumble CTF",
    url: "https://cybersecurityrumble.de/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-26T20:00:00+00:00",
    participants: 24,
    ctftime_url: "https://ctftime.org/event/1429/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "https://ctftime.org//media/events/social_chall_second_2.png",
    format_id: 1,
    id: 1429,
    ctf_id: 159,
  },
  {
    organizers: [{ id: 8241, name: "ISITDTU" }],
    onsite: false,
    finish: "2021-11-28T00:00:00+00:00",
    description:
      "Due to COVID-19, we are thinking about 3 options below, and we will announce you soon what is the final choice:\r\n\r\nOption 1: If everything are going well, the finals round will be held at the Duy Tan university in Da Nang, VietNam. Top 10 teams (5 international teams - 5 Vietnamese team and 5 members/teams) will be invited.\r\n\r\nOption 2: The finals round will be held at the Duy Tan university in Da Nang VietNam. Top 10 Vietnamese teams will be invited. And only one team of one university or company/organization is acceptable.\r\n\r\nOption 3: We will have an online event.\r\n\r\nInformation about the finals round, we will send invitation email to qualified team and update on our Facebook fanpage https://fb.com/isitdtu.",
    weight: 23.08,
    title: "ISITDTU CTF 2021 Quals",
    url: "https://ctf.isitdtu.com/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-27T00:00:00+00:00",
    participants: 13,
    ctftime_url: "https://ctftime.org/event/1464/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 1 },
    logo: "https://ctftime.org//media/events/logo_43_1.gif",
    format_id: 1,
    id: 1464,
    ctf_id: 258,
  },
  {
    organizers: [{ id: 3329, name: "Dragon Sector" }],
    onsite: false,
    finish: "2021-11-28T12:00:00+00:00",
    description:
      "<ul>\r\n<li>Format: online, jeopardy, team-based, no team size limit\r\n</li>\r\n<li>Categories: web, re, pwn, crypto, misc</li>\r\n<li>Contact (IRC): #dragonsector @ irc.libera.chat</li>\r\n<li>Contact (e-mail): ctf@dragonsector.pl</li>\r\n</ul>\r\n",
    weight: 99.33,
    title: "Dragon CTF 2021",
    url: "",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-11-27T12:00:00+00:00",
    participants: 24,
    ctftime_url: "https://ctftime.org/event/1457/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 1 },
    logo: "https://ctftime.org//media/events/avatar_3_1.jpg",
    format_id: 1,
    id: 1457,
    ctf_id: 103,
  },
  {
    organizers: [{ id: 60467, name: "pwnthem0le" }],
    onsite: true,
    finish: "2021-12-03T20:00:00+00:00",
    description:
      "Final event of m0leCon 2021. Prequalified teams from m0leCon CTF Teaser 2021 + teams of conference attendees only.",
    weight: 0.0,
    title: "m0leCon CTF 2021",
    url: "https://m0lecon.it/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-12-02T20:00:00+00:00",
    participants: 2,
    ctftime_url: "https://ctftime.org/event/1456/",
    location: "Italy, Turin",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 1 },
    logo: "https://ctftime.org//media/events/43934324789e71551206c5fe87cacb84.png",
    format_id: 1,
    id: 1456,
    ctf_id: 372,
  },
  {
    organizers: [{ id: 285, name: "Shellphish" }],
    onsite: false,
    finish: "2021-12-03T23:00:00+00:00",
    description:
      'The Shellphish iCTF contest is multi-site, multi-team hacking contest in which a number of teams compete independently against each other.\r\n\r\nIn traditional editions of the iCTF competition, the goal of each team is to maintain a set of services so that they remain available and uncompromised throughout the contest. \r\nEach team also has to attempt to compromise the other teams\' services. \r\nSince all the teams have access to an identical copy of the virtual host containing the vulnerable services, each team has to find vulnerabilities in their copy of the hosts and possibly fix the vulnerabilities without disrupting the services. \r\nAt the same time, the teams have to leverage their knowledge about the vulnerabilities they found to compromise the servers run by other teams.  \r\nCompromising a service allows a team to bypass the service\'s security mechanisms and to "capture the flag" associated with the service.\r\nThese flags are then presented to the organizers as "proof of compromise" to receive "attack" points.\r\nThe teams also receive "defense" points if they can keep their services functional and uncompromised.\r\n\r\nAt the end of competition, the team with the most points wins.\r\n\r\nUPDATE: Apologies, due to technical reasons we have to postpone this event to December, 3rd. We are committed to providing you guys with a fun game with cool challenges, however this is not possible at the current time. \r\n\r\nHopefully we can have the time of the event changed on CTFtime soon, in the meantime, we ask for your understanding and hope you enjoy our game in December :)',
    weight: 0.0,
    title: "iCTF 2020",
    url: "https://shellphish.net/ictf/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Attack-Defense",
    start: "2021-12-03T14:00:00+00:00",
    participants: 44,
    ctftime_url: "https://ctftime.org/event/1339/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 9, days: 0 },
    logo: "https://ctftime.org//media/events/shellphish_logo.png",
    format_id: 2,
    id: 1339,
    ctf_id: 5,
  },
  {
    organizers: [{ id: 72254, name: "MetaCTF" }],
    onsite: false,
    finish: "2021-12-05T20:00:00+00:00",
    description:
      "This event is free and open to everyone. Participants will compete in teams of up to 4, with separate scoreboards for students and non-students.\r\n\r\nThis CTF will challenge and encourage participants to learn new techniques and concepts related to cybersecurity, with problems covering topics such as web exploitation, cryptography, binary exploitation, reverse engineering, forensics, and reconnaissance.\r\n\r\nThroughout the CTF, we will be livestreaming a series of talks, problem walkthroughs, and sessions with well-known cybersecurity professionals! Participants will have opportunities to network with sponsors and recruiters.\r\n\r\nSponsorship information (including current sponsors) available on our website.",
    weight: 24.09,
    title: "MetaCTF CyberGames 2021",
    url: "https://metactf.com/cybergames",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-12-03T20:00:00+00:00",
    participants: 31,
    ctftime_url: "https://ctftime.org/event/1476/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 0, days: 2 },
    logo: "https://ctftime.org//media/events/MainM6_1.png",
    format_id: 1,
    id: 1476,
    ctf_id: 500,
  },
  {
    organizers: [{ id: 8299, name: "HITCON" }],
    onsite: false,
    finish: "2021-12-05T14:00:00+00:00",
    description: "",
    weight: 0.0,
    title: "HITCON CTF 2021",
    url: "https://ctf2021.hitcon.org/",
    is_votable_now: false,
    restrictions: "Open",
    format: "Jeopardy",
    start: "2021-12-04T02:00:00+00:00",
    participants: 9,
    ctftime_url: "https://ctftime.org/event/1460/",
    location: "",
    live_feed: "",
    public_votable: true,
    duration: { hours: 12, days: 1 },
    logo: "https://ctftime.org//media/events/hitcon2_5.png",
    format_id: 1,
    id: 1460,
    ctf_id: 79,
  },
];

const CtfList = ({ navigation }) => {
  return (
    <ScrollView>
      {ctfs.map((ctf) => (
        <CtfCard key={ctf.id} {...ctf} navigation={navigation} />
      ))}
    </ScrollView>
  );
};

export default CtfList;
